apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    component: backend
spec:
  rules:
    - host: mountain.skireports.home.seifts.us
      http:
        paths:
          - pathType: Prefix
            path: '/api/'
            backend:
              service:
                name: backend-internal-service
                port:
                  number: 5000
---
# LoadBalancer service for the backend
apiVersion: v1
kind: Service
metadata:
  name: backend-internal-service
  labels:
    component: backend
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    component: backend
  type: LoadBalancer
---
# Backend application deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    component: backend
spec:
  selector:
    matchLabels:
      component: backend
  replicas: 1
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: localhost:32000/backend
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: redis-url
#     initContainers:
#       - name: cache-warmer
#         image: localhost:32000/jobs
#         env:
#           - name: REDIS_URL
#             valueFrom:
#               configMapKeyRef:
#                 name: jobs-config
#                 key: redis-url
