apiVersion: networking.k8s.io/v1
kind: Ingress
medata:
  name: frontend-ingress
spec:
  rules:
    - host: beech.skireports.home.seifts.us
      paths:
        - pathType: Prefix
          path: '/'
          backend:
            service:
              name: frontend-service
              port:
                number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          image: localhost:32000/beech_frontend
          ports:
            - containerPort: 80
