apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    component: frontend
spec:
  rules:
    - host: beech.skireports.home.seifts.us
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: frontend-internal-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-internal-service
  labels:
    component: frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    component: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  selector:
    matchLabels:
      component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:32000/beech_frontend
          ports:
            - containerPort: 80
