#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: frontend-ingress
#  labels:
#    app: frontend
#spec:
#  rules:
#    - host: beech.skireports.home.seifts.us
#      paths:
#	- pathType: Prefix
#	  path: '/'
#	  backend:
#	    service:
#	      name: frontend-internal-service
#	      port:
#		number: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend-internal-service
#  labels:
#    app: frontend
#spec:
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#  selector:
#    app: frontend
#  type: LoadBalancer
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:32000/beech_frontend
          ports:
            - containerPort: 80
